{
 "title": "Inspektor Energiš",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor",
    "label": "Senzor",
    "query": "power_now,power_now_phase_1,power_now_phase_2,power_now_phase_3"
   },
   { "name": "always_on", "label": "Always On [W]", "query": "210" }
  ]
 },
 "panels": [
  {
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  last_updated AS \"time\",\n  state::integer as power\nFROM states\nWHERE\n  $__timeFilter(last_updated) and state not in ('unknown', 'unavailable', '') and entity_id = 'sensor.${sensor}'\nORDER BY last_updated;"
    },
    {
     "rawSql": "SELECT\n  ${always_on}::integer AS always_on,\n  unnest(array[to_timestamp(${__from}/1000) at time zone 'utc', to_timestamp(${__to}/1000) at time zone 'utc']) as time\nORDER by\n  time;"
    }
   ]
  },
  {
   "title": "Energie spočítaná z grafu",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH fragments_prev AS (\n  WITH fragments AS (\n    SELECT\n      last_updated AS time,\n      state::float AS value\n    FROM\n      states\n    WHERE\n      state NOT IN ('unknown', 'unavailable', '') AND\n      entity_id = 'sensor.${sensor}' AND\n      $__timeFilter(last_updated)\n  ) \n  SELECT\n    LAG(value, 1) OVER (ORDER BY time) AS value_prev,\n    LAG(time, 1) OVER (ORDER BY time) AS time_prev,\n    time\n  FROM\n    fragments\n)\nSELECT\n  SUM(value_prev * EXTRACT(EPOCH FROM (time - time_prev)) / 3600) AS energy,\n  (${always_on} * (($__to/1000.0 - $__from/1000.0) / 3600.0)) AS always_on\nFROM\n  fragments_prev"
    }
   ]
  },
  {
   "title": "Popis",
   "type": "text",
   "gridPos": { "h": 18, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "Pomocník pro výpočty energie \\[Wh\\] z okamžitých příkonů \\[W\\] jednotlivých fází či jejich součtu.\n\nPostup:\n\n* vyber senzor (fázi nebo jejich součet)\n* vyber přesné časové období, které chceš spočítat (vpravo nahoře nebo označením oblasti v grafu)\n* volitelně doplň hodnotu \"Always On\", která se od vypočítané hodnoty odečte (anebo ji nech na 0)\n\nPoznámka: kladné hodnoty v grafech vyjadřují spotřebu v domě, záporné přísun energie z gridu když nabíjím baterie\n\nNápověda:\n\n* Fáze 1: bojler, zásuvky kuchyň (gril, topinkovač, mixér, lednice)\n* Fáze 2: indukční deska, žebřík v koupelně, myčka, pila v dílně\n* Fáze 3: trouba, zásuvky v patře (žehlení, počítače), zásuvky sklep (prádelna, plynový kotel)"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  created AS \"time\",\n  mean\nFROM statistics_short_term\nWHERE\n  $__timeFilter(created)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Energie \"Always On\"",
   "type": "stat",
   "description": "V grafech je často vidět, že příkon [W] neklesá k nule a drží se trvale na konstantní hodnotě. To jsou spotřebiče, které odebírají energii ze stejné fáze. Pro přesnější výpočet je možné zadat do tohoto pole Watty, které se od hodnoty z grafu odečtou.",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Energie po odečtu \"Always On\"",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Časové období",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $__to/1000.0 - $__from/1000.0 AS value"
    }
   ]
  },
  {
   "title": "Poměr Always On a ostatní spotřeby",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 6 }
   ]
  }
 ]
}